In [4]:
%load_ext autoreload
%autoreload 2

import sys
import featuregraph as fg

from featuregraph.accumulation.accumulations import add_accumulation_signal

print("Python:", sys.executable)
print("FeatureGraph:", fg.__file__)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Python: /workspaces/featuregraph/.venv/bin/python
FeatureGraph: /workspaces/featuregraph/src/featuregraph/__init__.py

In [11]:
bidmc = fg.datasets.bidmc(
    subject=1,
)

In [13]:
bidmc = fg.oscillation.waves.add_wave_primitives(bidmc, ['respiration'])
bidmc = fg.oscillation.waves.add_wave_id(bidmc, ['respiration'], 'subject')
bidmc = fg.oscillation.waves.add_wave_features(bidmc, ['respiration'], 'respiration_wave_id')
bidmc

,time,respiration,ppg,ecg_v,ecg_avr,ecg_ii,subject,respiration_rising,respiration_falling,enter_respiration_rising,exit_respiration_rising,respiration_peak_index,respiration_trough_index,respiration_wave_id,respiration_rising_time,respiration_falling_time,respiration_amplitude,respiration_duration
0,0.000,0.35386,0.43597,0.52549,0.30392,0.72549,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
1,0.008,0.35679,0.43206,0.51961,0.33529,0.67059,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
2,0.016,0.35875,0.42815,0.51569,0.37451,0.60980,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
3,0.024,0.36168,0.42424,0.50588,0.41961,0.55098,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
4,0.032,0.36364,0.42131,0.50980,0.44902,0.50000,1,False,False,False,False,NaN,NaN,0,0,0,0.00733,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59996,479.970,0.15640,0.40567,0.50000,0.51961,0.40000,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
59997,479.980,0.15152,0.40371,0.50588,0.52941,0.39412,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
59998,479.980,0.14663,0.40176,0.50000,0.53529,0.38431,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
59999,479.990,0.14174,0.40176,0.50000,0.53922,0.38039,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37
60000,480.000,0.13783,0.40274,0.49412,0.53529,0.38039,1,False,True,False,False,59991.0,59964.0,554,27,10,0.02297,37

In [14]:
bidmc = add_accumulation_signal(
    bidmc,
    signals=["respiration"],
    thresholds={'respiration': 'group_mean'},
    group='respiration_wave_id'
)

In [17]:
bidmc.head(10)

,time,respiration,ppg,ecg_v,ecg_avr,ecg_ii,subject,respiration_rising,respiration_falling,enter_respiration_rising,...,respiration_peak_index,respiration_trough_index,respiration_wave_id,respiration_rising_time,respiration_falling_time,respiration_amplitude,respiration_duration,respiration_accumulation_threshold,respiration_accumulation_contribution,respiration_accumulation
0,0.000,0.35386,0.43597,0.52549,0.30392,0.72549,1,False,False,False,...,NaN,NaN,0,0,0,0.00733,0,0.363244,-0.009384,-9.384000e-03
1,0.008,0.35679,0.43206,0.51961,0.33529,0.67059,1,False,False,False,...,NaN,NaN,0,0,0,0.00733,0,0.363244,-0.006454,-1.583800e-02
2,0.016,0.35875,0.42815,0.51569,0.37451,0.60980,1,False,False,False,...,NaN,NaN,0,0,0,0.00733,0,0.363244,-0.004494,-2.033200e-02
3,0.024,0.36168,0.42424,0.50588,0.41961,0.55098,1,False,False,False,...,NaN,NaN,0,0,0,0.00733,0,0.363244,-0.001564,-2.189600e-02
4,0.032,0.36364,0.42131,0.50980,0.44902,0.50000,1,False,False,False,...,NaN,NaN,0,0,0,0.00733,0,0.363244,0.000396,-2.150000e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59996,479.970,0.15640,0.40567,0.50000,0.51961,0.40000,1,False,True,False,...,59991.0,59964.0,554,27,10,0.02297,37,0.161687,-0.005287,6.902811e-02
59997,479.980,0.15152,0.40371,0.50588,0.52941,0.39412,1,False,True,False,...,59991.0,59964.0,554,27,10,0.02297,37,0.161687,-0.010167,5.886108e-02
59998,479.980,0.14663,0.40176,0.50000,0.53529,0.38431,1,False,True,False,...,59991.0,59964.0,554,27,10,0.02297,37,0.161687,-0.015057,4.380405e-02
59999,479.990,0.14174,0.40176,0.50000,0.53922,0.38039,1,False,True,False,...,59991.0,59964.0,554,27,10,0.02297,37,0.161687,-0.019947,2.385703e-02
60000,480.000,0.13783,0.40274,0.49412,0.53529,0.38039,1,False,True,False,...,59991.0,59964.0,554,27,10,0.02297,37,0.161687,-0.023857,-1.387779e-16