In [13]:
# 2. Imports and connection
import os
import json

import featuregraph as fg
from featuregraph.storage import postgres as fg_postgres

os.environ["DATABASE_URL"] = "postgresql://postgres:password@localhost:5432/featuregraph"
conn = fg_postgres.connect()
print("connected")

connected

In [14]:
# 3. Construct the oscillation objects
bidmc = fg.datasets.bidmc(subject=1)

bidmc_oscillation = fg.oscillation.Oscillation(signals="respiration", group="subject", smooth_signal=False)
bidmc_oscillation_features = bidmc_oscillation.fit_transform(bidmc)
bidmc_oscillation_objects = bidmc_oscillation.summarize(bidmc_oscillation_features, signal="respiration")

tep = fg.datasets.eastman(fault_number=2, simulation_run=1)

tep_oscillation = fg.oscillation.Oscillation(signals='reactor_pressure', group=['fault_number', 'simulation_run'], smooth_signal=True)
tep_oscillation_features = tep_oscillation.fit_transform(tep)
tep_oscillation_objects = tep_oscillation.summarize(tep_oscillation_features, signal="reactor_pressure")

bidmc_oscillation_objects_table = bidmc_oscillation_objects.table
tep_oscillation_objects_table = tep_oscillation_objects.table

In [15]:
# 4. Define the schema (measurement columns shared across every oscillation
# study, plus provenance) and create both tables
oscillation_columns = {
    "oscillation_id": "BIGINT NOT NULL",
    "is_complete": "BOOLEAN NOT NULL",
    "start_index": "BIGINT NOT NULL",
    "peak_index": "BIGINT",
    "end_index": "BIGINT NOT NULL",
    "rise_duration": "DOUBLE PRECISION",
    "fall_duration": "DOUBLE PRECISION",
    "duration": "DOUBLE PRECISION NOT NULL",
    "period": "DOUBLE PRECISION",
    "amplitude": "DOUBLE PRECISION",
    "rising_mean_rate": "DOUBLE PRECISION",
    "falling_mean_rate": "DOUBLE PRECISION",
    "peak_rise_rate": "DOUBLE PRECISION",
    "peak_fall_rate": "DOUBLE PRECISION",
    "temporal_symmetry": "DOUBLE PRECISION",
    # provenance
    "dataset": "TEXT NOT NULL",
    "dataset_version": "TEXT NOT NULL",
    "construction_parameters": "JSONB NOT NULL",
    "featuregraph_version": "TEXT NOT NULL",
    "inserted_at": "TIMESTAMPTZ NOT NULL DEFAULT now()",
}

fg_postgres.create_table(
    conn, "bidmc_oscillations",
    {"subject": "BIGINT NOT NULL", **oscillation_columns},
    constraints=["PRIMARY KEY (subject, oscillation_id)"],
    if_exists="replace",
)
fg_postgres.create_table(
    conn, "tep_oscillations",
    {"fault_number": "BIGINT NOT NULL", "simulation_run": "BIGINT NOT NULL", **oscillation_columns},
    constraints=["PRIMARY KEY (fault_number, simulation_run, oscillation_id)"],
    if_exists="replace",
)
print("tables created")

tables created

In [16]:
# 5. Helpers: match dtypes to the schema, and attach provenance
integer_columns = ["oscillation_id", "start_index", "peak_index", "end_index"]

def prepare(frame):
    prepared = frame.copy()
    for column in integer_columns:
        if column in prepared:
            prepared[column] = prepared[column].astype("Int64")
    prepared["is_complete"] = prepared["is_complete"].astype("boolean")
    return prepared

def oscillation_parameters(oscillation) -> dict:
    """Every constructor parameter actually in effect, explicit or defaulted."""
    return vars(oscillation)

def with_provenance(frame, *, dataset, dataset_version, parameters):
    prepared = frame.copy()
    prepared["dataset"] = dataset
    prepared["dataset_version"] = dataset_version
    prepared["construction_parameters"] = json.dumps(parameters)
    prepared["featuregraph_version"] = fg.__version__
    return prepared

In [17]:
# 6. Insert
fg_postgres.insert_rows(
    conn, "bidmc_oscillations",
    with_provenance(
        prepare(bidmc_oscillation_objects_table),
        dataset="bidmc",
        dataset_version=bidmc.attrs["bidmc_version"],
        parameters=oscillation_parameters(bidmc_oscillation),
    ),
)
fg_postgres.insert_rows(
    conn, "tep_oscillations",
    with_provenance(
        prepare(tep_oscillation_objects_table),
        dataset="tep",
        dataset_version=tep.attrs["source_revision"],
        parameters=oscillation_parameters(tep_oscillation),
    ),
)
print("rows inserted")

rows inserted

In [19]:
# 7. Verify
display(fg_postgres.read_table(conn, "bidmc_oscillations"))
display(fg_postgres.read_table(conn, "tep_oscillations"))

,subject,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,period,...,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry,dataset,dataset_version,construction_parameters,featuregraph_version,inserted_at
0,1,1,True,9,13,79,4.0,66.0,70.0,NaN,...,0.087487,0.005302,0.001466,0.011535,0.114286,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
1,1,2,True,79,166,290,87.0,124.0,211.0,153.0,...,0.011146,0.007820,0.015445,0.019452,0.824645,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
2,1,3,True,290,298,364,8.0,66.0,74.0,132.0,...,0.030059,0.003643,0.000880,0.007038,0.216216,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
3,1,4,True,364,456,551,92.0,95.0,187.0,158.0,...,0.010466,0.010135,0.013490,0.026002,0.983957,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
4,1,5,True,551,576,641,25.0,65.0,90.0,120.0,...,0.014741,0.005670,0.004496,0.010753,0.555556,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,1,549,True,59443,59458,59524,15.0,66.0,81.0,46.0,...,0.051873,0.011789,0.001760,0.019844,0.370370,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
549,1,550,True,59524,59566,59619,42.0,53.0,95.0,108.0,...,0.005818,0.004611,0.004887,0.009873,0.884211,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
550,1,551,True,59619,59658,59676,39.0,18.0,57.0,92.0,...,0.002983,0.006462,0.004985,0.004496,0.631579,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
551,1,552,True,59676,59792,59878,116.0,86.0,202.0,134.0,...,0.007163,0.009662,0.011535,0.029227,0.851485,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
552,1,553,True,59878,59907,59963,29.0,56.0,85.0,115.0,...,0.009067,0.004696,0.004399,0.009482,0.682353,bidmc,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00

,fault_number,simulation_run,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,...,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry,dataset,dataset_version,construction_parameters,featuregraph_version,inserted_at
0,2,1,1,True,28,31,42,3.0,11.0,14.0,...,0.081867,0.022327,0.024867,0.026885,0.428571,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
1,2,1,2,True,42,68,125,26.0,57.0,83.0,...,0.099447,0.045362,0.101409,0.080290,0.626506,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
2,2,1,3,True,125,157,206,32.0,49.0,81.0,...,0.058058,0.037916,0.074132,0.061699,0.790123,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
3,2,1,4,True,206,237,259,31.0,22.0,53.0,...,0.045422,0.064003,0.091562,0.045042,0.830189,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
4,2,1,5,True,259,283,314,24.0,31.0,55.0,...,0.079376,0.061453,0.072563,0.119418,0.872727,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2,1,57,True,2758,2784,2810,26.0,26.0,52.0,...,0.049056,0.049056,0.069896,0.079484,1.000000,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
57,2,1,58,True,2810,2837,2866,27.0,29.0,56.0,...,0.056907,0.052982,0.086760,0.093279,0.964286,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
58,2,1,59,True,2866,2884,2912,18.0,28.0,46.0,...,0.057585,0.037019,0.058408,0.056972,0.782609,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
59,2,1,60,True,2912,2925,2928,13.0,3.0,16.0,...,0.020020,0.086755,0.035427,0.010005,0.375000,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
60,2,1,61,True,2928,2971,2992,43.0,21.0,64.0,...,0.027346,0.055994,0.069403,0.077500,0.656250,tep,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00

In [20]:
# 8. Comparison view across both datasets
with conn.cursor() as cursor:
    cursor.execute("""
        CREATE OR REPLACE VIEW oscillations AS
        SELECT
            dataset,
            subject::text AS group_id,
            oscillation_id, is_complete, start_index, peak_index, end_index,
            rise_duration, fall_duration, duration, period, amplitude,
            rising_mean_rate, falling_mean_rate, peak_rise_rate, peak_fall_rate,
            temporal_symmetry,
            dataset_version, construction_parameters, featuregraph_version, inserted_at
        FROM bidmc_oscillations
        UNION ALL
        SELECT
            dataset,
            fault_number::text || '_' || simulation_run::text AS group_id,
            oscillation_id, is_complete, start_index, peak_index, end_index,
            rise_duration, fall_duration, duration, period, amplitude,
            rising_mean_rate, falling_mean_rate, peak_rise_rate, peak_fall_rate,
            temporal_symmetry,
            dataset_version, construction_parameters, featuregraph_version, inserted_at
        FROM tep_oscillations
    """)
conn.commit()
print("view created")

view created

In [23]:
# 9. Verify — compare the two datasets directly
display(fg_postgres.read_table(conn, "oscillations"))

,dataset,group_id,oscillation_id,is_complete,start_index,peak_index,end_index,rise_duration,fall_duration,duration,...,amplitude,rising_mean_rate,falling_mean_rate,peak_rise_rate,peak_fall_rate,temporal_symmetry,dataset_version,construction_parameters,featuregraph_version,inserted_at
0,bidmc,1,1,True,9,13,79,4.0,66.0,70.0,...,0.174974,0.087487,0.005302,0.001466,0.011535,0.114286,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
1,bidmc,1,2,True,79,166,290,87.0,124.0,211.0,...,0.484849,0.011146,0.007820,0.015445,0.019452,0.824645,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
2,bidmc,1,3,True,290,298,364,8.0,66.0,74.0,...,0.120235,0.030059,0.003643,0.000880,0.007038,0.216216,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
3,bidmc,1,4,True,364,456,551,92.0,95.0,187.0,...,0.481427,0.010466,0.010135,0.013490,0.026002,0.983957,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
4,bidmc,1,5,True,551,576,641,25.0,65.0,90.0,...,0.184262,0.014741,0.005670,0.004496,0.010753,0.555556,1.0.0,"{'eps': 0.0, 'group': 'subject', 'signals': ['...",0.1.0b1,2026-09-06 17:51:32.051311+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,tep,2_1,57,True,2758,2784,2810,26.0,26.0,52.0,...,0.637729,0.049056,0.049056,0.069896,0.079484,1.000000,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
610,tep,2_1,58,True,2810,2837,2866,27.0,29.0,56.0,...,0.768244,0.056907,0.052982,0.086760,0.093279,0.964286,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
611,tep,2_1,59,True,2866,2884,2912,18.0,28.0,46.0,...,0.518262,0.057585,0.037019,0.058408,0.056972,0.782609,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
612,tep,2_1,60,True,2912,2925,2928,13.0,3.0,16.0,...,0.130132,0.020020,0.086755,0.035427,0.010005,0.375000,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00
613,tep,2_1,61,True,2928,2971,2992,43.0,21.0,64.0,...,0.587938,0.027346,0.055994,0.069403,0.077500,0.656250,309b944f35ac440ff0c70616947ffe723c766e14,"{'eps': 0.0, 'group': ['fault_number', 'simula...",0.1.0b1,2026-09-06 17:51:32.149824+00:00